"""Add Reservation model

Revision ID: 0827818be7a5
Revises: 8d3f44adf867
Create Date: 2026-05-02 17:20:33.398755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0827818be7a5'
down_revision: Union[str, None] = '8d3f44adf867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('from_reserve', sa.DateTime(), nullable=False),
    sa.Column('to_reserve', sa.DateTime(), nullable=False),
    sa.Column('meetingroom_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meetingroom_id'], ['meetingroom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    # ### end Alembic commands ###
